# Generated by Django 4.1.7 on 2023-04-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=1000)),
                ('cuerpo', models.CharField(max_length=99999)),
                ('autor', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
